<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-09-13T20:31:39" tests="0" file="cypress/integration/Front-End/Homepage.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Homepage" timestamp="2022-09-13T20:31:39" tests="1" time="0.0000" failures="1">
    <testcase name="Homepage Usu치rio dever치 realizar acesso a homepage do sistema" time="0.0000" classname="Usu치rio dever치 realizar acesso a homepage do sistema">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It&apos;s possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

https://on.cypress.io/cross-origin-script-error" type="Error"><![CDATA[Error: The following error originated from your application code, not from Cypress.

  > Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

https://on.cypress.io/cross-origin-script-error
]]></failure>
    </testcase>
  </testsuite>
</testsuites>