<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-09-19T19:37:37" tests="0" file="cypress/integration/Back-End/cy.teste" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="GET usuarios" timestamp="2022-09-19T19:37:37" tests="1" time="0.0000" failures="1">
    <testcase name="GET usuarios busca usuários corretamente" time="0.0000" classname="busca usuários corretamente">
      <failure message="`cy.request()` failed on:

https://auth.padrao-qa2.webpremios.digital/oauth2/userInfo

The response we received from your web server was:

  &gt; 400: Bad Request

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://auth.padrao-qa2.webpremios.digital/oauth2/userInfo
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/9.7.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;*/*&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;
}

-----------------------------------------------------------

The response we got was:

Status: 400 - Bad Request
Headers: {
  &quot;content-type&quot;: &quot;application/json;charset=UTF-8&quot;,
  &quot;content-length&quot;: &quot;77&quot;,
  &quot;connection&quot;: &quot;keep-alive&quot;,
  &quot;date&quot;: &quot;Mon, 19 Sep 2022 19:37:41 GMT&quot;,
  &quot;x-amzn-requestid&quot;: &quot;39b965b9-6dec-429b-aa0b-2c745adad4e9&quot;,
  &quot;x-xss-protection&quot;: &quot;1; mode=block&quot;,
  &quot;strict-transport-security&quot;: &quot;max-age=31536000 ; includeSubDomains&quot;,
  &quot;x-amz-cognito-request-id&quot;: &quot;21671e06-0c0a-4f2b-b7e0-f3b86e9e733e&quot;,
  &quot;x-frame-options&quot;: &quot;DENY&quot;,
  &quot;x-amzn-remapped-connection&quot;: &quot;close&quot;,
  &quot;set-cookie&quot;: [
    &quot;XSRF-TOKEN=d4d3836e-59b4-4298-a258-435d44d914d8; Path=/; Secure; HttpOnly; SameSite=Lax&quot;
  ],
  &quot;x-amz-apigw-id&quot;: &quot;YuO4bEQ5oAMFssQ=&quot;,
  &quot;cache-control&quot;: &quot;no-cache, no-store, max-age=0, must-revalidate&quot;,
  &quot;x-amzn-remapped-server&quot;: &quot;Server&quot;,
  &quot;x-content-type-options&quot;: &quot;nosniff&quot;,
  &quot;expires&quot;: &quot;0&quot;,
  &quot;x-amzn-remapped-www-authenticate&quot;: &quot;Bearer realm=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_II8KXhipn, error=INVALID_REQUEST&quot;,
  &quot;x-amzn-trace-id&quot;: &quot;Root=1-6328c502-6755ad1a00241663217f2aa4;Sampled=0&quot;,
  &quot;pragma&quot;: &quot;no-cache&quot;,
  &quot;x-application-context&quot;: &quot;application:prod:8443&quot;,
  &quot;x-amzn-remapped-date&quot;: &quot;Mon, 19 Sep 2022 19:37:41 GMT&quot;,
  &quot;x-cache&quot;: &quot;Error from cloudfront&quot;,
  &quot;via&quot;: &quot;1.1 257bf616e82b7bdb9c0b2562445411f0.cloudfront.net (CloudFront)&quot;,
  &quot;x-amz-cf-pop&quot;: &quot;GRU3-C2&quot;,
  &quot;x-amz-cf-id&quot;: &quot;M9pn8h-vHOV7yvzzgLh4qUyHk4BH-a-PLCmn8fnDuD7xQkkHqFD6xw==&quot;
}
Body: {
  &quot;error&quot;: &quot;invalid_request&quot;,
  &quot;error_description&quot;: &quot;No authorization header set&quot;
}


https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

https://auth.padrao-qa2.webpremios.digital/oauth2/userInfo

The response we received from your web server was:

  > 400: Bad Request

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://auth.padrao-qa2.webpremios.digital/oauth2/userInfo
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/9.7.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 400 - Bad Request
Headers: {
  "content-type": "application/json;charset=UTF-8",
  "content-length": "77",
  "connection": "keep-alive",
  "date": "Mon, 19 Sep 2022 19:37:41 GMT",
  "x-amzn-requestid": "39b965b9-6dec-429b-aa0b-2c745adad4e9",
  "x-xss-protection": "1; mode=block",
  "strict-transport-security": "max-age=31536000 ; includeSubDomains",
  "x-amz-cognito-request-id": "21671e06-0c0a-4f2b-b7e0-f3b86e9e733e",
  "x-frame-options": "DENY",
  "x-amzn-remapped-connection": "close",
  "set-cookie": [
    "XSRF-TOKEN=d4d3836e-59b4-4298-a258-435d44d914d8; Path=/; Secure; HttpOnly; SameSite=Lax"
  ],
  "x-amz-apigw-id": "YuO4bEQ5oAMFssQ=",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "x-amzn-remapped-server": "Server",
  "x-content-type-options": "nosniff",
  "expires": "0",
  "x-amzn-remapped-www-authenticate": "Bearer realm=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_II8KXhipn, error=INVALID_REQUEST",
  "x-amzn-trace-id": "Root=1-6328c502-6755ad1a00241663217f2aa4;Sampled=0",
  "pragma": "no-cache",
  "x-application-context": "application:prod:8443",
  "x-amzn-remapped-date": "Mon, 19 Sep 2022 19:37:41 GMT",
  "x-cache": "Error from cloudfront",
  "via": "1.1 257bf616e82b7bdb9c0b2562445411f0.cloudfront.net (CloudFront)",
  "x-amz-cf-pop": "GRU3-C2",
  "x-amz-cf-id": "M9pn8h-vHOV7yvzzgLh4qUyHk4BH-a-PLCmn8fnDuD7xQkkHqFD6xw=="
}
Body: {
  "error": "invalid_request",
  "error_description": "No authorization header set"
}


https://on.cypress.io/request
    at http://localhost:59974/__cypress/runner/cypress_runner.js:165434:80
    at tryCatcher (http://localhost:59974/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (http://localhost:59974/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (http://localhost:59974/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (http://localhost:59974/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (http://localhost:59974/__cypress/runner/cypress_runner.js:11139:18)
    at _drainQueueStep (http://localhost:59974/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (http://localhost:59974/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:59974/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (http://localhost:59974/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (http://localhost:59974/__cypress/tests?p=cypress\integration\Back-End\cy.teste:100:10)]]></failure>
    </testcase>
  </testsuite>
</testsuites>